spring:
  datasource:
    url: jdbc:h2:mem:testdb # In-memory database named 'testdb'
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # Enable the H2 console
      path: /h2-console # Path to access the H2 console
      settings:
        trace: false
        web-allow-others: false # Restrict remote access to the console
  jpa:
    hibernate:
      ddl-auto: update # Automatically create/update schema based on entities
    show-sql: true # Log SQL statements to the console
    database-platform: org.hibernate.dialect.H2Dialect